development:
  adapter: mysql2
  database: demo
  pool: 5
  username: username
  password: password
  timeout: 5000

test:
  adapter: mysql2
  database: demo
  pool: 5
  username: username
  password: password
  timeout: 5000

production:
  adapter: mysql2
  database: demo
  pool: 5
  username: username
  password: password
  timeout: 5000
